/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './notifier-message.component.ngfactory';
import * as import2 from '../../../tmp/lib/notifier-message.component';
import * as import3 from '@angular/platform-browser';
import * as import4 from '../../../tmp/lib/notifier.service';
import * as import5 from '@angular/common';
import * as import6 from '../../../tmp/lib/max.pipe';
import * as import7 from '../../../tmp/lib/notifier-container.component';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '../../../tmp/lib/notifier-options.service';
const styles_NotifierContainerComponent:any[] = ['*[_ngcontent-%COMP%], [_ngcontent-%COMP%]::after, [_ngcontent-%COMP%]::before{-moz-box-sizing:border-box;box-sizing:border-box}.notifier-wrapper[_ngcontent-%COMP%]{position:fixed}.notifier-wrapper.left[_ngcontent-%COMP%]{left:16px;left:1rem}.notifier-wrapper.bottom[_ngcontent-%COMP%]{bottom:16px;bottom:1rem}.notifier-wrapper.right[_ngcontent-%COMP%]{right:16px;right:1rem}.notifier-wrapper.top[_ngcontent-%COMP%]{top:16px;top:1rem}.notifier-wrapper.center[_ngcontent-%COMP%]{left:50%;-webkit-transform:translateX(-50%);-moz-transform:translateX(-50%);-ms-transform:translateX(-50%);transform:translateX(-50%)}'];
export const RenderType_NotifierContainerComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_NotifierContainerComponent,
  data: {}
}
);
function View_NotifierContainerComponent_2(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng2-notifier-message',([] as any[]),(null as any),(null as any),(null as any),import1.View_NotifierMessageComponent_0,import1.RenderType_NotifierMessageComponent)),
    import0.ɵdid(122880,(null as any),0,import2.NotifierMessageComponent,[
      import3.DomSanitizer,
      import4.NotifierService
    ]
      ,{notice: [
        0,
        'notice'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_NotifierContainerComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'notifier-wrapper'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(139264,(null as any),0,import5.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
    ,{
      klass: [
        0,
        'klass'
      ]
      ,
      ngClass: [
        1,
        'ngClass'
      ]

    }
    ,(null as any)),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),2,(null as any),View_NotifierContainerComponent_2)),
    import0.ɵdid(401408,(null as any),0,import5.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import0.ɵppd(2)
  ]
  ,(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = 'notifier-wrapper';
    const currVal_1:any = co.position;
    ck(v,1,0,currVal_0,currVal_1);
    const currVal_2:any = import0.ɵunv(v,3,0,ck(v,4,0,import0.ɵnov((<any>v.parent),0),co.notices,co.maxStack));
    ck(v,3,0,currVal_2);
  },(null as any));
}
export function View_NotifierContainerComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵpid(0,import6.MaxPipe,([] as any[])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_NotifierContainerComponent_1)),
    import0.ɵdid(8192,(null as any),0,import5.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import7.NotifierContainerComponent = v.component;
    const currVal_0:any = co.notices;
    ck(v,2,0,currVal_0);
  },(null as any));
}
function View_NotifierContainerComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-notifier-container',([] as any[]),(null as any),(null as any),(null as any),View_NotifierContainerComponent_0,RenderType_NotifierContainerComponent)),
    import0.ɵdid(122880,(null as any),0,import7.NotifierContainerComponent,[
      import8.Store,
      [
        2,
        import9.NotifierOptions
      ]

    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const NotifierContainerComponentNgFactory:import0.ComponentFactory<import7.NotifierContainerComponent> = import0.ɵccf('app-notifier-container',import7.NotifierContainerComponent,View_NotifierContainerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhbmllbHBhbi9Eb2N1bWVudHMvZGV2ZWxvcG1lbnQvcHJvamVjdHMvcGVyc29uYWwvYW5ndWxhcjIvbmcyLW5vdGlmaWNhdGlvbi90bXAvbGliL25vdGlmaWVyLWNvbnRhaW5lci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZGFuaWVscGFuL0RvY3VtZW50cy9kZXZlbG9wbWVudC9wcm9qZWN0cy9wZXJzb25hbC9hbmd1bGFyMi9uZzItbm90aWZpY2F0aW9uL3RtcC9saWIvbm90aWZpZXItY29udGFpbmVyLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2RhbmllbHBhbi9Eb2N1bWVudHMvZGV2ZWxvcG1lbnQvcHJvamVjdHMvcGVyc29uYWwvYW5ndWxhcjIvbmcyLW5vdGlmaWNhdGlvbi90bXAvbGliL25vdGlmaWVyLWNvbnRhaW5lci5jb21wb25lbnQudHMuTm90aWZpZXJDb250YWluZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2RhbmllbHBhbi9Eb2N1bWVudHMvZGV2ZWxvcG1lbnQvcHJvamVjdHMvcGVyc29uYWwvYW5ndWxhcjIvbmcyLW5vdGlmaWNhdGlvbi90bXAvbGliL25vdGlmaWVyLWNvbnRhaW5lci5jb21wb25lbnQudHMuTm90aWZpZXJDb250YWluZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwibm90aWZpZXItd3JhcHBlclwiICpuZ0lmPVwibm90aWNlc1wiIFtuZ0NsYXNzXT1cInBvc2l0aW9uXCI+PG5nMi1ub3RpZmllci1tZXNzYWdlICpuZ0Zvcj1cImxldCBtZXNzYWdlIG9mIG5vdGljZXN8IG1heDogbWF4U3RhY2tcIiBbbm90aWNlXT1cIm1lc3NhZ2VcIj48L25nMi1ub3RpZmllci1tZXNzYWdlPjwvZGl2PiIsIjxhcHAtbm90aWZpZXItY29udGFpbmVyPjwvYXBwLW5vdGlmaWVyLWNvbnRhaW5lcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBbUU7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7O0lBQXFFO0lBQXJFLFNBQXFFLFNBQXJFOzs7OztNQUFuRTtRQUFBO1FBQUE7TUFBQTtJQUFBO2dCQUFBOzs7OztJQUFBO0tBQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQW1FO2dCQUFBOzs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO2dCQUFzQjs7OztJQUFwRjtJQUF5QztJQUE5QyxTQUFLLFVBQXlDLFNBQTlDO0lBQXlGO0lBQXRCLFNBQXNCLFNBQXRCOzs7Ozs7SUFBbkU7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7OztJQUE4QjtJQUE5QixTQUE4QixTQUE5Qjs7Ozs7SUNBQTtnQkFBQTs7TUFBQTtRQUFBOztNQUFBOztJQUFBO0tBQUE7OztJQUFBOzs7In0=
