/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../tmp/lib/notifier.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '@ngrx/store/src/ng2';
import * as import5 from '@angular/platform-browser';
import * as import6 from '@angular/platform-browser/animations';
import * as import7 from '@ngrx/store/src/dispatcher';
import * as import8 from './notifier-container.component.ngfactory';
import * as import9 from '../../../tmp/lib/messages.reducer';
import * as import10 from '@angular/animations/browser';
import * as import11 from '@ngrx/store/src/reducer';
import * as import12 from '@ngrx/store/src/state';
import * as import13 from '@ngrx/store/src/store';
class NotifierModuleInjector extends import0.ɵNgModuleInjector<import1.NotifierModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _StoreModule_3:import4.StoreModule;
  _ErrorHandler_4:any;
  _APP_INITIALIZER_5:any[];
  _ApplicationInitStatus_6:import0.ApplicationInitStatus;
  _ɵf_7:import0.ɵf;
  _ApplicationRef_8:any;
  _ApplicationModule_9:import0.ApplicationModule;
  _BrowserModule_10:import5.BrowserModule;
  _BrowserAnimationsModule_11:import6.BrowserAnimationsModule;
  _NotifierModule_12:import1.NotifierModule;
  __LOCALE_ID_13:any;
  __NgLocalization_14:import2.NgLocaleLocalization;
  __ɵi_15:import3.ɵi;
  __Compiler_16:import0.Compiler;
  __APP_ID_17:any;
  __IterableDiffers_18:any;
  __KeyValueDiffers_19:any;
  __DomSanitizer_20:import5.ɵe;
  __Sanitizer_21:any;
  __HAMMER_GESTURE_CONFIG_22:import5.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_23:any[];
  __EventManager_24:import5.EventManager;
  __ɵDomSharedStylesHost_25:import5.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_26:import5.ɵDomRendererFactory2;
  __AnimationDriver_27:any;
  __ɵAnimationStyleNormalizer_28:any;
  __ɵAnimationEngine_29:import6.ɵa;
  __RendererFactory2_30:any;
  __ɵSharedStylesHost_31:any;
  __Testability_32:import0.Testability;
  __Meta_33:import5.Meta;
  __Title_34:import5.Title;
  __Dispatcher_35:import7.Dispatcher;
  __INITIAL_REDUCER_36:any;
  __INITIAL_REDUCER_37:any;
  __Reducer_38:any;
  __INITIAL_STATE_39:any;
  __INITIAL_STATE_40:any;
  __State_41:any;
  __Store_42:any;
  constructor(parent:import0.Injector) {
    super(parent,[import8.NotifierContainerComponentNgFactory],([] as any[]));
  }
  get _LOCALE_ID_13():any {
    if ((this.__LOCALE_ID_13 == null)) { (this.__LOCALE_ID_13 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_13;
  }
  get _NgLocalization_14():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_14 == null)) { (this.__NgLocalization_14 = new import2.NgLocaleLocalization(this._LOCALE_ID_13)); }
    return this.__NgLocalization_14;
  }
  get _ɵi_15():import3.ɵi {
    if ((this.__ɵi_15 == null)) { (this.__ɵi_15 = new import3.ɵi()); }
    return this.__ɵi_15;
  }
  get _Compiler_16():import0.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import0.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import0.ɵg()); }
    return this.__APP_ID_17;
  }
  get _IterableDiffers_18():any {
    if ((this.__IterableDiffers_18 == null)) { (this.__IterableDiffers_18 = import0.ɵl()); }
    return this.__IterableDiffers_18;
  }
  get _KeyValueDiffers_19():any {
    if ((this.__KeyValueDiffers_19 == null)) { (this.__KeyValueDiffers_19 = import0.ɵm()); }
    return this.__KeyValueDiffers_19;
  }
  get _DomSanitizer_20():import5.ɵe {
    if ((this.__DomSanitizer_20 == null)) { (this.__DomSanitizer_20 = new import5.ɵe(this.parent.get(import5.DOCUMENT))); }
    return this.__DomSanitizer_20;
  }
  get _Sanitizer_21():any {
    if ((this.__Sanitizer_21 == null)) { (this.__Sanitizer_21 = this._DomSanitizer_20); }
    return this.__Sanitizer_21;
  }
  get _HAMMER_GESTURE_CONFIG_22():import5.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_22 == null)) { (this.__HAMMER_GESTURE_CONFIG_22 = new import5.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_22;
  }
  get _EVENT_MANAGER_PLUGINS_23():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_23 == null)) { (this.__EVENT_MANAGER_PLUGINS_23 = [
      new import5.ɵDomEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵKeyEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵHammerGesturesPlugin(this.parent.get(import5.DOCUMENT),this._HAMMER_GESTURE_CONFIG_22)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_23;
  }
  get _EventManager_24():import5.EventManager {
    if ((this.__EventManager_24 == null)) { (this.__EventManager_24 = new import5.EventManager(this._EVENT_MANAGER_PLUGINS_23,this.parent.get(import0.NgZone))); }
    return this.__EventManager_24;
  }
  get _ɵDomSharedStylesHost_25():import5.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_25 == null)) { (this.__ɵDomSharedStylesHost_25 = new import5.ɵDomSharedStylesHost(this.parent.get(import5.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_25;
  }
  get _ɵDomRendererFactory2_26():import5.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_26 == null)) { (this.__ɵDomRendererFactory2_26 = new import5.ɵDomRendererFactory2(this._EventManager_24,this._ɵDomSharedStylesHost_25)); }
    return this.__ɵDomRendererFactory2_26;
  }
  get _AnimationDriver_27():any {
    if ((this.__AnimationDriver_27 == null)) { (this.__AnimationDriver_27 = import6.ɵb()); }
    return this.__AnimationDriver_27;
  }
  get _ɵAnimationStyleNormalizer_28():any {
    if ((this.__ɵAnimationStyleNormalizer_28 == null)) { (this.__ɵAnimationStyleNormalizer_28 = import6.ɵc()); }
    return this.__ɵAnimationStyleNormalizer_28;
  }
  get _ɵAnimationEngine_29():import6.ɵa {
    if ((this.__ɵAnimationEngine_29 == null)) { (this.__ɵAnimationEngine_29 = new import6.ɵa(this._AnimationDriver_27,this._ɵAnimationStyleNormalizer_28)); }
    return this.__ɵAnimationEngine_29;
  }
  get _RendererFactory2_30():any {
    if ((this.__RendererFactory2_30 == null)) { (this.__RendererFactory2_30 = import6.ɵd(this._ɵDomRendererFactory2_26,this._ɵAnimationEngine_29,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_30;
  }
  get _ɵSharedStylesHost_31():any {
    if ((this.__ɵSharedStylesHost_31 == null)) { (this.__ɵSharedStylesHost_31 = this._ɵDomSharedStylesHost_25); }
    return this.__ɵSharedStylesHost_31;
  }
  get _Testability_32():import0.Testability {
    if ((this.__Testability_32 == null)) { (this.__Testability_32 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_32;
  }
  get _Meta_33():import5.Meta {
    if ((this.__Meta_33 == null)) { (this.__Meta_33 = new import5.Meta(this.parent.get(import5.DOCUMENT))); }
    return this.__Meta_33;
  }
  get _Title_34():import5.Title {
    if ((this.__Title_34 == null)) { (this.__Title_34 = new import5.Title(this.parent.get(import5.DOCUMENT))); }
    return this.__Title_34;
  }
  get _Dispatcher_35():import7.Dispatcher {
    if ((this.__Dispatcher_35 == null)) { (this.__Dispatcher_35 = new import7.Dispatcher()); }
    return this.__Dispatcher_35;
  }
  get _INITIAL_REDUCER_37():any {
    if ((this.__INITIAL_REDUCER_37 == null)) { (this.__INITIAL_REDUCER_37 = import4._initialReducerFactory(this.__INITIAL_REDUCER_36)); }
    return this.__INITIAL_REDUCER_37;
  }
  get _Reducer_38():any {
    if ((this.__Reducer_38 == null)) { (this.__Reducer_38 = import4._reducerFactory(this._Dispatcher_35,this._INITIAL_REDUCER_37)); }
    return this.__Reducer_38;
  }
  get _INITIAL_STATE_40():any {
    if ((this.__INITIAL_STATE_40 == null)) { (this.__INITIAL_STATE_40 = import4._initialStateFactory(this.__INITIAL_STATE_39,this._INITIAL_REDUCER_37)); }
    return this.__INITIAL_STATE_40;
  }
  get _State_41():any {
    if ((this.__State_41 == null)) { (this.__State_41 = import4._stateFactory(this._INITIAL_STATE_40,this._Dispatcher_35,this._Reducer_38)); }
    return this.__State_41;
  }
  get _Store_42():any {
    if ((this.__Store_42 == null)) { (this.__Store_42 = import4._storeFactory(this._Dispatcher_35,this._Reducer_38,this._State_41)); }
    return this.__Store_42;
  }
  createInternal():import1.NotifierModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._StoreModule_3 = new import4.StoreModule();
    this._ErrorHandler_4 = import5.ɵa();
    this._APP_INITIALIZER_5 = [
      import0.ɵo,
      import5.ɵc(this.parent.get(import5.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_6 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_5);
    this._ɵf_7 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_4,this.componentFactoryResolver,this._ApplicationInitStatus_6);
    this._ApplicationRef_8 = this._ɵf_7;
    this._ApplicationModule_9 = new import0.ApplicationModule(this._ApplicationRef_8);
    this._BrowserModule_10 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._BrowserAnimationsModule_11 = new import6.BrowserAnimationsModule();
    this._NotifierModule_12 = new import1.NotifierModule();
    this.__INITIAL_REDUCER_36 = {messages: import9.messagesReducer};
    this.__INITIAL_STATE_39 = (undefined as any);
    return this._NotifierModule_12;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.StoreModule)) { return this._StoreModule_3; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_4; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_5; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_6; }
    if ((token === import0.ɵf)) { return this._ɵf_7; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_8; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_9; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_10; }
    if ((token === import6.BrowserAnimationsModule)) { return this._BrowserAnimationsModule_11; }
    if ((token === import1.NotifierModule)) { return this._NotifierModule_12; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_13; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_14; }
    if ((token === import3.ɵi)) { return this._ɵi_15; }
    if ((token === import0.Compiler)) { return this._Compiler_16; }
    if ((token === import0.APP_ID)) { return this._APP_ID_17; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_18; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_19; }
    if ((token === import5.DomSanitizer)) { return this._DomSanitizer_20; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_21; }
    if ((token === import5.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_22; }
    if ((token === import5.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_23; }
    if ((token === import5.EventManager)) { return this._EventManager_24; }
    if ((token === import5.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_25; }
    if ((token === import5.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_26; }
    if ((token === import10.AnimationDriver)) { return this._AnimationDriver_27; }
    if ((token === import10.ɵAnimationStyleNormalizer)) { return this._ɵAnimationStyleNormalizer_28; }
    if ((token === import10.ɵAnimationEngine)) { return this._ɵAnimationEngine_29; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_30; }
    if ((token === import5.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_31; }
    if ((token === import0.Testability)) { return this._Testability_32; }
    if ((token === import5.Meta)) { return this._Meta_33; }
    if ((token === import5.Title)) { return this._Title_34; }
    if ((token === import7.Dispatcher)) { return this._Dispatcher_35; }
    if ((token === import4._INITIAL_REDUCER)) { return this.__INITIAL_REDUCER_36; }
    if ((token === import4.INITIAL_REDUCER)) { return this._INITIAL_REDUCER_37; }
    if ((token === import11.Reducer)) { return this._Reducer_38; }
    if ((token === import4._INITIAL_STATE)) { return this.__INITIAL_STATE_39; }
    if ((token === import4.INITIAL_STATE)) { return this._INITIAL_STATE_40; }
    if ((token === import12.State)) { return this._State_41; }
    if ((token === import13.Store)) { return this._Store_42; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_7.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_25 && this._ɵDomSharedStylesHost_25.ngOnDestroy());
  }
}
export const NotifierModuleNgFactory:import0.NgModuleFactory<import1.NotifierModule> = new import0.NgModuleFactory<any>(NotifierModuleInjector,import1.NotifierModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhbmllbHBhbi9Eb2N1bWVudHMvZGV2ZWxvcG1lbnQvcHJvamVjdHMvcGVyc29uYWwvYW5ndWxhcjIvbmcyLW5vdGlmaWNhdGlvbi90bXAvbGliL25vdGlmaWVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9kYW5pZWxwYW4vRG9jdW1lbnRzL2RldmVsb3BtZW50L3Byb2plY3RzL3BlcnNvbmFsL2FuZ3VsYXIyL25nMi1ub3RpZmljYXRpb24vdG1wL2xpYi9ub3RpZmllci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
